#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      auto: eth0
      dhcp4: no
      addresses:
        - "{{ .container.network.host }}"
      gateway4: "{{ .container.network.gateway }}"
