#cloud-config
write_files:
  - path: /etc/start.sh
    permissions: "0755"
    content: |
      #!/bin/sh
      set -x      
      export http_proxy=http://{{ index .config "hab.plateform.host.v4.address"  }}:{{ index .config "hab.egress.listen.port" }}
      export https_proxy=http://{{ index .config "hab.plateform.host.v4.address"  }}:{{ index .config "hab.egress.listen.port" }}
      export no_proxy=localhost,.local,.localdomain
      export HTTP_PROXY=http://{{ index .config "hab.plateform.host.v4.address"  }}:{{ index .config "hab.egress.listen.port" }}
      export HTTPS_PROXY=http://{{ index .config "hab.plateform.host.v4.address"  }}:{{ index .config "hab.egress.listen.port" }}
      export NO_PROXY=localhost,.local,.localdomain
      /bin/sh || exit 0

  - path: /etc/deploy.sh
    encoding: b64
    permissions: "0755"
    content: "{{ .container.deploy  }}"

  - path: /etc/undeploy.sh
    encoding: b64
    permissions: "0755"
    content: "{{ .container.undeploy }}"

apk_repos:
  alpine_repo:
    community_enabled: false
    testing_enabled: false
    version: "v3.20"
timezone: Europe/Paris
runcmd:
  - rc-update add networking boot
  - rc-service networking start
