#cloud-config
write_files:
  - path: /etc/start.sh
    permissions: "0755"
    content: |
      #!/bin/sh
      set -x      
      export http_proxy=http://{{ .hab.lxd.lxc.host.address  }}:{{ .hab.egress.listen.port }}
      export no_proxy=localhost,.local,.localdomain
      export HTTP_PROXY=http://{{ .hab.lxd.lxc.host.address  }}:{{ .hab.egress.listen.port }}
      export NO_PROXY=localhost,.local,.localdomain
      /bin/sh || exit 0
apk_repos:
  alpine_repo:
    base_url: http://{{ .hab.lxd.lxc.host.address  }}:{{ .hab.egress.listen.port }}/os/alpine
    community_enabled: false
    testing_enabled: false
    version: "3.20"
timezone: Europe/Paris
runcmd:
  - rc-update add networking boot
  - rc-service networking start
