#cloud-config
write_files:
  - path: /etc/start.sh
    permissions: "0755"
    content: |
      #!/bin/sh
      PROXY_URL={{ .container.proxy.scheme }}://{{ .container.proxy.host }}:{{ .container.proxy.port }}
      PROXY_BYPASS={{or .container.proxy.bypass "localhost,.local,.localdomain" }}
      export http_proxy=${PROXY_URL}
      export https_proxy=${PROXY_URL}
      export no_proxy=${PROXY_BYPASS}
      export HTTP_PROXY=${PROXY_URL}
      export HTTPS_PROXY=${PROXY_URL}
      export NO_PROXY=${PROXY_BYPASS}
      if [ -f /etc/motd ]; then
        cat /etc/motd
      fi
      /bin/sh || exit 0

  - path: /etc/deploy.sh
    encoding: b64
    permissions: "0755"
    content: "{{ .container.deploy  }}"

  - path: /etc/undeploy.sh
    encoding: b64
    permissions: "0755"
    content: "{{ .container.undeploy }}"

apk_repos:
  alpine_repo:
    community_enabled: false
    testing_enabled: false
    version: "v3.20"
timezone: Europe/Paris
runcmd:
  - rc-update add networking boot
  - rc-service networking start
