#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - "{{ .container.network.v4.host }}/{{ .container.network.v4.mask }}"
        - "{{ .container.network.v6.host }}/{{ .container.network.v6.mask }}"
      gateway4: "{{ .container.network.v4.gateway }}"
      gateway6: "{{ .container.network.v6.gateway }}"
