hab.storage.root: ".hab"
hab.logs.level: "INFO"
hab.logs.path: "./logs"
hab.snap.command.prefix: "sudo"
hab.snap.command.name: "snap"
hab.rm.prefix: "sudo"
hab.rm.name: "rm"
hab.pki.path: "./pki"
hab.pki.ca.common_name: "Hab CA"
hab.pki.ca.organization: "Hab Org"
hab.pki.ca.organization_unit: "Hab PKI Unit"
hab.pki.ca.locality: "Paris"
hab.pki.ca.province: "IDF"
hab.pki.ca.country: "FR"
hab.pki.certs.egress.common_name: "Hab Egress"
hab.pki.certs.egress.organization: "Hab Org"
hab.pki.certs.egress.organization_unit: "Hab PKI Unit"
hab.pki.certs.egress.locality: "Paris"
hab.pki.certs.egress.province: "IDF"
hab.pki.certs.egress.country: "FR"
hab.lxd.snap: "lxd"
hab.lxd.snap_mode: ""
hab.lxd.command.prefix: "sudo"
hab.lxd.command.name: "lxd"
hab.lxd.lxc.profile: "hab"
hab.lxd.lxc.host.interface: "hab0"
hab.lxd.lxc.host.address: "10.33.0.254"
hab.lxd.lxc.host.netmask: "24"
hab.lxd.lxc.host.nat: "true"
hab.lxd.lxc.storage.pool: "hab"
hab.lxd.lxc.storage.driver: "dir"
hab.lxd.lxc.storage.path: "./lxd"
hab.lxd.lxc.command.prefix: "sudo"
hab.lxd.lxc.command.name: "lxc"
hab.distrobuilder.snap: "distrobuilder"
hab.distrobuilder.snap_mode: "--classic"
hab.distrobuilder.command.prefix: "sudo"
hab.distrobuilder.command.name: "distrobuilder"
hab.distrobuilder.build.path: ./distrobuilder
hab.containers.path: "./containers"
hab.egress.listen.port: "58050"
hab.ingress.listen.host: "127.0.0.1"
hab.ingress.listen.port.http: "58051"
hab.ingress.listen.port.https: "58052"
