hab.name: "hab"
hab.storage.root: ".hab"
hab.logs.level: "INFO"
hab.logs.path: "./logs"

hab.commands.snap: "snap"
hab.commands.snap.prefix: "sudo"
hab.commands.rm: "rm"
hab.commands.rm.prefix: "sudo"

hab.distrobuilder.snap: "distrobuilder"
hab.distrobuilder.snap_mode: "--classic"
hab.distrobuilder.command.prefix: "sudo"
hab.distrobuilder.command.name: "distrobuilder"
hab.distrobuilder.build.path: ./distrobuilder

hab.plateform.snap: "lxd"
hab.plateform.snap_mode: ""
hab.plateform.storage.driver: "dir"
hab.plateform.storage.path: "./plateform"

hab.plateform.host.v4.address: "10.77.0.254"
hab.plateform.host.v4.netmask: "24"
hab.plateform.host.v4.nat: "false"
hab.plateform.host.v6.address: "fd42:73ab:7e08:9d01::ff/64"
hab.plateform.host.v6.nat: "false"

hab.plateform.command.prefix: "sudo"
hab.plateform.command: "lxc"

hab.containers.path: "./containers"

hab.pki.path: "./pki"
hab.pki.certs.locality: "Paris"
hab.pki.certs.province: "Ile de France"
hab.pki.certs.country: "FR"
hab.pki.certs.organization: "k-hab setup"
hab.pki.certs.organization_unit: "k-hab setup"

hab.pki.ca.common_name: ".hab.k"
hab.pki.ingress.common_name: ".ingress.hab.k"
hab.pki.ingress.dns_names: "hab.local"

hab.egress.listen.port: "58050"

hab.ingress.listen.host: "127.0.0.1"
hab.ingress.listen.port.http: "58051"
hab.ingress.listen.port.https: "58052"
