hab.storage.root: ".hab"
hab.logs.level: "INFO"
hab.logs.path: "./logs"

hab.commands.snap: "snap"
hab.commands.snap.prefix: "sudo"
hab.commands.apt: "apt-get"
hab.commands.apt.prefix: "sudo"
hab.commands.dpkg: "dpkg-query"
hab.commands.dpkg.prefix: ""
hab.commands.systemctl: "systemctl"
hab.commands.systemctl.prefix: "sudo"

hab.commands.ps: "ps"
hab.commands.ps.prefix: "sudo"


hab.commands.rm: "rm"
hab.commands.rm.prefix: "sudo"

 

hab.apt.command.prefix: "sudo"
hab.apt.command.name: "apt-get"
 
hab.pki.path: "./pki"
hab.pki.ca.common_name: "Hab CA"
hab.pki.ca.organization: "Hab Org"
hab.pki.ca.organization_unit: "Hab PKI Unit"
hab.pki.ca.locality: "Paris"
hab.pki.ca.province: "IDF"
hab.pki.ca.country: "FR"
hab.pki.certs.ingress.common_name: "Hab Ingress"
hab.pki.certs.ingress.organization: "Hab Org"
hab.pki.certs.ingress.organization_unit: "Hab PKI Unit"
hab.pki.certs.ingress.locality: "Paris"
hab.pki.certs.ingress.province: "IDF"
hab.pki.certs.ingress.country: "FR"
hab.pki.certs.ingress.dns_names: "hab.local"
hab.incus.apt.server: "incus"
hab.incus.apt.client: "incus-client"
hab.incus.apt.dnsmasq: "dnsmasq-base"
hab.incus.command.prefix: "sudo"
hab.incus.command.name: "incus"

hab.incus.storage.pool: "hab"
hab.incus.storage.driver: "dir"
hab.incus.storage.path: "./incus"

hab.incus.host.interface: "hab0"
hab.incus.host.v4.address: "10.77.0.254"
hab.incus.host.v4.netmask: "24"
hab.incus.host.v4.nat: "false"

hab.incus.host.v6.address: "fd42:73ab:7e08:9d01::ff/64"
hab.incus.host.v6.nat: "false"

hab.incus.profile: "hab"


hab.distrobuilder.snap: "distrobuilder"
hab.distrobuilder.snap_mode: "--classic"
hab.distrobuilder.command.prefix: "sudo"
hab.distrobuilder.command.name: "distrobuilder"
hab.distrobuilder.build.path: ./distrobuilder
hab.containers.path: "./containers"
hab.egress.listen.port: "58050"
hab.ingress.listen.host: "127.0.0.1"
hab.ingress.listen.port.http: "58051"
hab.ingress.listen.port.https: "58052"
