config:
  hab.entry.container: "bastion"
containers:
  - name: "bastion"
    base: alpine
    shell: "/etc/start.sh"
    network:
      host: "10.33.0.1"
      mask: "24"
      gateway: "10.33.0.254"
    proxy:
      port: "58050"
    deploy: |
      #!/bin/sh
      set -x
      touch /root/salut.txt
    undeploy: |
      #!/bin/sh
      set -x
      rm -f /root/salut.txt
