snap:
  command:
    prefix: "sudo"
    name: "snap"
lxd:
  snap: "lxd"
  snap_mode: ""
  command:
    prefix: "sudo"
    name: "lxd"
  lxc:
    profile: "hab"
    host:
      interface: "hab0"
      address: "10.33.0.254"
      netmask: "24"
      nat: "true"
    storage:
      pool: "hab"
      driver: "dir"
      path: ".out/lxd"
    command:
      prefix: "sudo"
      name: "lxc"
distrobuilder:
  snap: "distrobuilder"
  snap_mode: "--classic"
  command:
    prefix: "sudo"
    name: "distrobuilder"
  build:
    path: .out/distrobuilder
egress:
  listen:
    port: "58050"
  mirrors:
    alpine: "https://eu.edge.kernel.org/alpine/v"

ingress:
  listen:
    host: "127.0.0.1"
    port:
      http: "58051"
      https: "58052"
entry:
  container: "bastion"
