on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - run: make test
      - run: make release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/k-hab-linux-amd64
