on: push
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - run: make test
